tests/test-cookies.js, tests/test-follow-all-303.js, tests/test-follow-all.js, tests/test-form-data.js, tests/test-form-urlencoded.js, tests/test-form.js, tests/test-gzip.js, tests/test-hawk.js, tests/test-http-signature.js, tests/test-httpModule.js, tests/test-multipart.js, tests/test-onelineproxy.js, tests/test-rfc3986.js
server.close() is async, so treat it as such:
http://nodejs.org/api/net.html#net_server_close_callback
This doesn't seem to matter when test files are run in separate
processes using `npm test`, but it does when they are run in the same
process for the coverage report.
@simov fyi (hopefully this is the only issue with our coverage reporting)
=> Fix errors generating coverage reports.

package.json
Whenever you run `npm test` it would generate a file.
The location of the file would be `tests/browser/test-browser.js`
which is a directory that the linter will lint.
I tried making the linter ignore the file but it seems we're using
an older version of the linter which may not support ignoring paths.
I may be wrong but this was an alternative solution, safely delete
the file before running the linter.
=> Add clean script to remove test-browser.js after the tests run

README.md
Bearer tokens were incompletely documented, and wrap lines and clean up
some wording.
=> Improve auth docs

tests/test-agentOptions.js, tests/test-basic-auth.js, tests/test-bearer-auth.js, tests/test-body.js, tests/test-defaults.js, tests/test-digest-auth.js, tests/test-emptyBody.js, tests/test-event-forwarding.js, tests/test-headers.js, tests/test-https.js, tests/test-isUrl.js, tests/test-json-request.js, tests/test-node-debug.js, tests/test-option-reuse.js, tests/test-params.js, tests/test-piped-redirect.js, tests/test-pipes.js, tests/test-pool.js, tests/test-proxy-connect.js, tests/test-proxy.js, tests/test-redirect-auth.js, tests/test-redirect-complex.js, tests/test-redirect.js, tests/test-timeout.js, tests/test-toJSON.js, tests/test-unix.js
Somehow I missed a whole bunch of these in #1327.  Maybe I was only searching for `server.close()` and not `s.close()`?
Ping @simov
=> Always wait for server.close() callback in tests

README.md
Per discussion on Gitter and in #1277 we want to disable Coveralls PR
comments.  Add a Coveralls badge so that we still watch coverage stats.
While we're at it, add a Travis badge, and make all badges the same
style.
=> Clean up readme badges, and add Travis and Coveralls badges

request.js, tests/test-form-data-error.js
As per #1336 created a clean request which passes tests.
Below is a stack trace (from 1st October 2014 sorry it's old!) caused by uploading an image to the Facebook API using request. The trace is caught by a node domain otherwise it'd be ignored.
```
Error: write ECONNRESET Error: write ECONNRESET
at errnoException (net.js:904:11)
at afterWrite (net.js:720:19)
---------------------------------------------
at Readable.on (_stream_readable.js:707:33)
at pipe (tls.js:1455:10)
at exports.connect (tls.js:1352:19)
at Agent.createConnection (https.js:79:14)
at Agent.createSocket (http.js:1293:16)
at Agent.addRequest (http.js:1269:23)
at new ClientRequest (http.js:1416:16)
at exports.request (https.js:123:10)
---------------------------------------------
at Stream.pipe (stream.js:57:10)
at …
```
=> Emit FormData error events as Request error events

tests/test-form-data.js, tests/test-form.js, tests/test-multipart.js, tests/test-piped-redirect.js, tests/test-rfc3986.js
This is a less commonly used port than 8080 so it is less likely to
conflict with other services.  See discussion at #1327.
=> Standardize test ports on 6767

lib/getProxyFromURI.js, request.js
The getProxyFromURI function seems like a good candidate to remove from the
request.js file. That file is bloated and this fits well as a module.
This is still in need of a few more changes, but I figured people can start reviewing.
@simov @FredKSchott @nylen review?
=> getProxyFromURI Extraction Refactor

package.json, tests/browser/test.js
Turns out that if browser requests are erroring out on an early stage (this could be error on DNS, cross-domain security cancellation or user has no internet connection), request will fail when trying the method `caseless.has`, because this will invoke Object.keys on undefined. So just wrapping the check here in a check for headers fixes the issue.
I also added a browesr test for this. The test proves the problem: it will fail if request.js is not updated (for example with this code).
I realize I could have also sent a PR to caseless to avoid calling Object keys on an undefined object, but seems to me that we should not even invoke caseless when we have no headers to work with. 
Please let me know if you feel this should be solved in another way
Have a great week!
=> Make sure we return on errored browser requests.

README.md
The current url of travis-ci badge redirects you to https://travis-ci.org/nylen/chronolog, the image shows build status of that repository.
=> Correct travis-ci badge

request.js
Just moving stuff out of the huge function. I'm starting from the most obvious things.
=> Move digest auth into private prototype method

lib/auth.js, request.js
**WIP**
I moved the `auth` method logic into separate file. The `auth` method is split into two methods `basic` and `bearer`. Also I moved `_digest` and the part of the code in `onRequestResponse` related to these 3 methods.
The reasons to move exactly these functions is as follows: all private flags `_hasAuth`, ` _sentAuth` and private variables `_bearer`,` _user`, `_pass` are local for the `Auth` class. That way `request` now knows only about only 3 distinct methods `_auth.basic`, `_auth.bearer` and `_auth.response` versus 6 variables `_hasAuth`, `_sentAuth`, `_bearer`, `_user`, `_pass` and `_digest`
The `Auth` class keeps a pointer to the `request` instance, but only use it to modify the headers, as well as reading some values (as I said private variables related to the `Auth` class …
=> Refactor basic, bearer, digest auth logic into separate class

lib/oauth.js, request.js, tests/test-oauth.js
This is a follow up to my previous PR https://github.com/request/request/pull/1350 Also it might be related to this one https://github.com/request/request/pull/1360
The `getParams` function is about the generation of OAuth parameters. I think it's pretty straightforward to understand which parameters have defaults, which are excluded, and what parameters are required for the OAuth signature.
The `concatParams` function is the old `buildSortedParams` but I though it deserves it's own function, I mean the `oa` parameter was used from the outer scope, so it was not exactly a function in that sense.
One change in `concatParams` is that the signature is no longer appended to the end of the string, but that can be changed if it not confront to the spec in some way.
The `oauth` function is …
=> Refactor OAuth into separate module

README.md, request.js, tests/test-proxy.js, tests/test-tunnel.js
Before, tunneling would default to false for http destinations and be
forced to true for https destinations.
Now, allow specifying `tunnel : false` to perform a regular GET request
to HTTPS destinations.  This is insecure, so make a note accordingly.
Supersedes #1344 and fixes #1293.
Also add some more tests for proxy environment variables - it hasn't been easy to test proxying HTTPS URLs without tunneling until this change.
=> Allow explicitly disabling tunneling for proxied https destinations

request.js
Revise the `setupTunnel` function in `request.js`
Review? @nylen @simov @FredKSchott
=> Revise Setup Tunnel Function

package.json
the dependency 
``form-data`` is using ``"mime-types": "~2.0.3"``
https://github.com/felixge/node-form-data/blob/master/package.json#L20
but in ``request`` we are using ``~1.0.1`` which causes multiple version of copy being download whenever we require ``request``
=> Upgrade mime-types package version

README.md
Emphasise when the OS-wide TCP timeout overrules the `timeout` option. The previous explanation could leave the reader thinking that the OS-wide timeout would overrule a bigger `timeout` option even if the TCP connection was successfully established
=> Improve `timeout` option description

request.js, tests/test-rfc3986.js
Example `{json:{}}` or `{body:{}, json:true}`
Related to https://github.com/request/request/pull/1315
Closes https://github.com/request/request/issues/1395
Also take a look at the [options section](https://github.com/request/request#requestoptions-callback) of the documentation.
=> Do not rfc3986 escape JSON bodies

lib/auth.js, lib/multipart.js, lib/oauth.js, lib/redirect.js, package.json, request.js, tests/test-basic-auth.js
Closes #1400 
Closes #1406 
Closes #1407 
Fixes #1409
Fixes #1412 
Again on top of the previous 3 PRs. @nylen I think we should release a new version after this fix goes in.
=> Fix basic auth

README.md
Hopefully we can get rid of this soon!
=> Add note that the project is broken in 0.12.x

index.js, tests/test-errors.js
Currently it only throws the error if you make the request using `request.head(uri)`
This PR updates to also throw the error when making the request by manually setting the method
```javascript
request({
uri: uri,
method: 'HEAD'
})
```
=> Throw error when making HEAD request with a body

index.js, tests/test-defaults.js
Right now if you set a `requester` function in `request.defaults` it will override all further defined `requester` functions when using `request.METHOD` to make a request. For example
```javascript
var request1 = request.defaults({}, function(uri, options, callback){
console.log('I AM THE FIRST REQUESTER FUNCTION');
request(uri, options, callback);
})
var request2 = request1.defaults({}, function(uri, options, callback){
console.log('I AM THE SECOND REQUESTER FUNCTION');
console.log('I WILL NEVER GET CALLED BY request2.METHOD');
request1(uri, options, callback);
})
// currently using request.METHOD will only hit the first requester
request2.get(url)
// I AM THE FIRST REQUESTER FUNCTION
// using request directly will hit the both requesters
request({
uri: url,
method: 'GET'
})
// I AM THE …
```
=> Fix recursive requester

lib/multipart.js, tests/test-multipart-encoding.js, tests/test-multipart.js
Fixes https://github.com/request/request/issues/1416
The problem here was with poorly written logic about the boundary field in multipart/related content-type header. Now we allow fully qualified multipart headers, including ones containing their own boundary, in that case the boundary property is set from the content-header for that instance (see test-multipart.js)
I've done some major refactoring on the chunked detection tests and moved them to test-multipart-chunked.js I also fixed the logic where the transfer-encoding header overrides the value set through the chunked key, because the header wasn't removed anyway, and I don't think that should be the case either. Probably the previous tests were not catching this edge case.
=> Allow fully qualified multipart content-type header

index.js, tests/test-defaults.js
This PR adds the ability to call `request.defaults()` and only pass in a `requester` function.
Right now if you want to use defaults to just pass in a custom `requester` function you need to pass in an empty options object, like this...  
`request.defaults({}, function(uri, options, callback){})`
This PR adds the ability to do...  
```
request.defaults(function(uri, options, callback){})
// note we left out the first param of `{}`
```
=> Add ability to set a requester without setting default options

.travis.yml
=> Deprecate Node v0.8.x

README.md, request.js, tests/test-timing.js
Sure, it'd be fairly trivial to grab timestamps before initiating the request, and in the response callback, and compare them; on the other hand, I'll eventually have a _lot_ of tests where I want to use the functionality, and writing a wrapper around the request library doesn't appeal to me.
=> Add option to time request/response cycle (including rollup of redirects)

request.js, tests/test-baseUrl.js
I found a bug in new `baseUrl` feature, when used in combination with redirection.
This script produce absurdly error `[Error: options.uri must be a string when using options.baseUrl]`:
```javascript
var request = require('./node_modules/request');
var http = require('http');
var s = http.createServer(function(req, res) {
if(req.url === '/redirect/') {
res.writeHead(302, {
location : '/'
})
} else  {
res.statusCode = 200
}
res.end()
}).listen(6767);
request({
url: '/',
baseUrl: 'http://localhost:6767/redirect'
}, function (err, resp, body) {
console.log(err);
s.close();
});
```
This is due to the fact that first call changes URI to an object, and therefore in the second iteration (to redirected page) can be seen as a string. The solution is delete `baseUrl` immediately after use, because …
=> Fix baseUrl and redirections.

lib/auth.js, tests/test-basic-auth.js
Going by RFC 2617, it seems that a colon is required in the base64 encoded user-pass.
```
To receive authorization, the client sends the userid and password,
separated by a single colon (":") character, within a base64 [7]
encoded string in the credentials.
basic-credentials = base64-user-pass
base64-user-pass  = <base64 [4] encoding of user-pass, except not limited to 76 char/line>
user-pass   = userid ":" password
userid      = *<TEXT excluding ":">
password    = *TEXT
```
https://www.ietf.org/rfc/rfc2617.txt
Some servers handle the case of a missing colon, but others do not. For instance, the standard method in Golang for parsing basic auth requires a colon.
http://golang.org/src/net/http/request.go?s=16575:16641#L518
Rather than force users to specify an empty string, it would be …
=> Require Colon in Basic Auth

lib/helpers.js, tests/test-basic-auth.js
This fixes a bug that I have currently. Some users were created with special characters in password but could not authenticate through request.auth method afterward.
=> Parameters encoded to base 64 should be decoded as UTF-8, not ASCII.

README.md, package.json, request.js, tests/test-qs.js
Closes https://github.com/request/request/issues/1473
The `qsOptions` key can be used to pass options to both the `parse` and the `stringify` methods of the `qs` and `querystring` modules.
The `arrayFormat` options was missing from the `qs` readme https://github.com/hapijs/qs/pull/72
=> Add support for qs options via qsOptions key

README.md
- Add table of contents in readme
- Add back to top links at the end of each section
- Add horizontal line divider after each section
- Add visual cues in options list
Closes https://github.com/request/request/issues/1340
Also related to https://github.com/request/request/pull/1331
Basically I refactored the readme according to what @nylen outlined in https://github.com/request/request/issues/1340#issuecomment-69367275 as collaborative effort to improve the readme.
Easier to review the this PR would be to just check out the rendered markdown file https://github.com/simov/request/tree/refactor-readme
Table of contents and back to top links at the end of each section are pretty self explanatory. The horizontal line divider between the sections is mostly for easier maintenance of the file …
=> Add table of contents in readme

lib/auth.js, tests/test-bearer-auth.js
I noticed a couple of scenarios the other day:
0.  When no authentication mechanism is defined, or bearer = undefined (I meant to send it, but it got set incorrectly) the error message is difficult to deciper
0.  When setting `bearer: null`, request does a string concat, which results in `'bearer null'`. Probably not the intended behavior
Also added explanations to the bearer tests
=> Adding handling for no auth method and null bearer

package.json, tests/test-agent.js
@nicolasmccurdy Adding a test for https://github.com/request/request/issues/1472. This passes on node 0.10 and fails on 0.12.x and iojs
Closes https://github.com/request/request/issues/1472
=> Add a test for the forever agent

README.md, lib/har.js, package.json, request.js, tests/fixtures/har.json, tests/server.js, tests/test-har.js
passing a [HAR Request 1.2](http://www.softwareishard.com/blog/har-12-spec/#request) in `options.har` will construct and set matching `options` values for use in the request.
this makes the library particularly useful when dealing with debug / performance data from many tools and proxies, especially to repeat requests from the browser's network panel.
=> HTTP Archive 1.2 support

index.js, tests/test-defaults.js
Fixes https://github.com/request/request/issues/1506
=> Allow static invoking of convenience methods

index.js, tests/test-defaults.js
Fixes https://github.com/request/request/issues/1509
Introduced in https://github.com/request/request/pull/1429 https://github.com/request/request/pull/1430 follow up https://github.com/request/request/pull/1435
Related to this bug as well https://github.com/request/request/pull/1515
Calling a convenience method from default object wasn't using the defaults properties, because the method was not wrapped, and therefore the extend logic wasn't called at all.
Then I'm temporarily passing a string to the wrap function so that I can make the head-body check before calling the requester just to satisfy the https://github.com/request/request/blob/master/tests/test-defaults.js#L265 test.
I'm going to improve the entire defaults related logic in index.js after this PR got merged in, because it's …
=> Fix defaults

package.json, tests/test-promise.js
A few promise tests using [bluebird](https://github.com/petkaantonov/bluebird) as it seems to be the most popular promise solution atm, plus it's used by [request-promise](https://github.com/tyabonil/request-promise) internally.
This is in attempt to make the promise support first class citizen in request, as it turns out that a lot of people are using promises with request. Also these tests should cover the bugs found in https://github.com/request/request/issues/1506 and https://github.com/request/request/issues/1509
@kytwb @noseglid @ericlu88 @carsy @neverfox let me know if there is anything else that can be added as test cases here.
=> Add promise tests

request.js, tests/test-defaults.js, tests/test-headers.js
=> Delete request headers with undefined value.

index.js, lib/helpers.js, tests/test-defaults.js
This is a follow up to https://github.com/request/request/pull/1518
Much more simplified defaults and params initialization in index.js. Basically flattened the logic, also moved the `wrap` closure outside of the `defaults` method and I left it in index.js because I think it's very closely related to the `request` method, and the convenience http verb methods. Also completely dropped all of the object extend closures, as I don't think they add any substantial value to that piece of code.
/cc @nylen @FredKSchott @mikeal
=> Refactor defaults

package.json
seems like some folks have had issues when using request from source with `har-validator` dependency (see: https://github.com/ahmadnassri/har-validator/issues/6) `v1.6.1` of `har-validator` addresses these problems.
=> ensure the latest version of har-validator is included

.eslintrc, lib/helpers.js, lib/multipart.js, package.json, request.js, tests/test-baseUrl.js
I updated eslint to 0.18.0 and added a couple rules for style consistency.
```
// Use if () { }
//       ^ space
"space-after-keywords": [2, "always"],
```
There were only a few instances of `if()` and `else{` in the code, so this was clear.
```
// Use if () { }
//          ^ space
"space-before-blocks": [2, "always"],
```
There were only a few instances of `if (){` in the code, so this was also clear.
```
// Use function test() { }
//                 ^^ no space
"space-before-function-paren": [2, "never"]
```
This one was harder.  There were tons of `function ()`s and `function name ()`s in the code, including `function Request ()`.  But there were way more `function()`s and `function name()`s.  Introducing with `"always"` created 739 errors, vs `"never"` creating 245.
One additional …
=> More eslint

tests/test-agentOptions.js, tests/test-har.js, tests/test-https.js
Added 3 test fixes that was causing the coveralls build to fail (check out the comments).
Coveralls is now using the GitHub's status API to report the coverage status (instead of using comments) So this will make the merge status bar color change based on the coverage results, just like any other build error do. Decrease in coverage will be considered a warning. Click on the _Show all checks_ button below.
=> Fix coveralls

lib/oauth.js, request.js, tests/test-oauth.js
[Original thread](https://github.com/request/oauth-sign/issues/15) to add [oauth_body_hash signing](https://oauth.googlecode.com/svn/spec/ext/body_hash/1.0/oauth-bodyhash.html).
This isn't quite ready. Just looking for feedback to see if things look right so far.
Still needs tests and also support for body payloads other than json
cc: @simov
=> initial support for oauth_body_hash on json payloads

request.js
When the response content is piped through additional streams for decoding (e.g. for gzip decompression), pause and resume calls should be propagated to the last stream in the pipeline so that back pressure propagates correctly.
This avoids an issue where simultaneous back pressure from the content decoding stream and from a stream to which Request is piped could cause the response stream to get stuck waiting for a drain event on the content decoding stream which never occurs.  See #1567 for an example.
This commit also renames `dataStream` to `responseContent` to remedy my previous poor choice of name, since the name will be exposed on the Request instance it should be clearer and closer to the name used to refer to this data in the relevant RFCs.
Fixes #1567
=> Fix stall when piping gzipped response

lib/auth.js, lib/multipart.js, lib/oauth.js, request.js, tests/test-bearer-auth.js, tests/test-oauth.js
Related to this https://github.com/request/request/issues/1318#issuecomment-97374120 onward 
Any code that previously relied on catching the errors in the `catch` block will now receive them in the `callback` as errors if a `callback` is specified
```js
request({uri:'...'}, function (err, res, body) {
if (err) {
// all errors are received here
}
}).on('error', function (err) {
// that's being called before being registered
})
```
This repository still have two error cases that throws in index.js But if the callback is missing, any error will be thrown anyway
```js
try {
request({uri:'...'}).on('error', function (err) {
// that's being called before being registered
})
} catch (err) {
// EventEmitter throws the error if the event is unhandled
}
```
```js
request({uri:'...'}, function (err, …
```
=> Emit error instead of throw

lib/redirect.js, package.json, request.js, tests/test-gzip.js, tests/test-pipes.js
This PR fixes a bit of fallout due to overlooking the pause behavior before the response arrives in #1568 last night.  I added some additional tests which should help catch similar issues in the future.  
If anyone has ideas for how to avoid the arbitrary `setTimeout`s when testing `pause`/`resume`, that would be great (currently it waits a bit between sending chunks to allow pausing and waits a bit more after calling `pause` to confirm no more data arrives).  Also, if there is a better location for the tests, I'm open to moving them around too.
Due to #1568, we now propagate pause and resume to the response content stream, rather than the response stream.  However, when pause is called before the response arrives, the pause is still being applied to the response object directly.  Fix …
=> Fix pause before response arrives

tests/server.js, tests/test-body.js, tests/test-pipes.js
I came across some tests in the test-body.js that didn't seem to be actually asserting anything.
It seems that assertions are only being done if there is an expectBody property and if the value of the expectBody property is a Buffer, otherwise it won't run an assertion and just pass. To make matters even more complicated some of the tests don't give an expectBody property, so I'm not completely sure how to fix those tests. Just wanted to bring this to our attention.
=> Discovered tests that weren't properly running

lib/oauth.js, request.js, tests/test-oauth.js
- Cache the initial oauth options passed to request in _oauth.params
- On subsequent calls to init() use the cached _oauth.params
to invoke the oauth params generation logic again
Fixes #1573
=> Refresh the oauth_nonce on redirect (#1573)

README.md
Fixing the documentation to recommend using `options.ca`, `options.cer`, `options.key` and `options.passphrase` instead of `options.agentOptions.` homologues, to avoid trouble in proxied environments, as commented in #1583
=> Fixing documentation regarding TLS options (#1583)

tests/test-defaults.js
Hopefully this will make the maintenance of these tests a bit easier, because even with all functions folded is hard to constantly jump back and forth just to follow a single test. Also the tests are actually using tape now instead of assert and some dummy assertion in the request's callback.
Comments here #1430 and in subsequent PRs as well.
=> Refactor test-default tests (according to comments in #1430)

README.md, lib/auth.js, lib/redirect.js, request.js
- Moved `removeRefererHeader` to the appropriate section of the options docs
- Pass `options` to the redirect's module `onRequest` method, as it makes it more obvious from where these options are coming from (the extending of the request object in the ctor is a bit unexpected to say the least)
- Attached the `debug` function to the request's prototype to make it accessible to the modules through the request instance<br>
This also fixes the `request.debug` call in the `har` module, which obviously is not covered by the tests atm, or rather it should be obvious if coveralls was actually working ..
=> A few minor fixes:

index.js
I changed the way they are defined so that they are more IDE-friendly. The way they were defined, an IDE wouldn't easily recognize them and would often show 'request.get' or 'request.post' etc as a possible error. Ctrl+clicking on the 'get' function wouldn't take you to where it was defined. Now it will!
=> fix the way http verbs are defined

request.js, tests/ssl/ca/localhost.js, tests/ssl/ca/server.js
Actually, it's not only deprecated, checking it with `.hasOwnProperty('client')` is broken in 2.2.0, but that's going to be fixed in 2.2.1.
See https://github.com/nodejs/io.js/pull/1572 https://github.com/nodejs/io.js/issues/1850 [nodejs/io.js#1852/files](https://github.com/nodejs/io.js/pull/1852/files)
=> Replace '.client' with '.socket' as the former was deprecated in 2.2.0.

.travis.yml, README.md, package.json
Fixes #1577 (hopefully)
From what I'm reading coveralls no longer works with the public token for some reason. Codeclimate, codeship and now coveralls requires full read/write access to all of your public/private repos + the org ones = which is insane IMO.
Codecov on the other hand requires minimal set of permissions for public projects + it seems that they support reporting via the GitHub status API.
=> Migrate to codecov

lib/oauth.js, tests/test-oauth.js
I broke it here https://github.com/simov/request/commit/41319044e602af69cdfad9a92dc0c4fd4d30db0a#diff-84fad1d3b3913ec86805e857580c5d54R114 because the OAuth parameters were appended here https://github.com/simov/request/commit/41319044e602af69cdfad9a92dc0c4fd4d30db0a#diff-ccc0734f65dd7a299409ff07d35be095L1398 instead of replaced.
Additionally now `request.uri` is constructed properly when using OAuth `transport_method:query`, so when using `request-debug` the correct `uri` is dumped containing all of the query parameters.
Lastly I greatly improved the OAuth transport_method related tests, because they were a bit loose and the cause of this bug in the first place.
=> Fix OAuth query transport_method

index.js, package.json, tests/server.js, tests/test-defaults.js
@mikeal @nylen I'm introducing the [extend](https://www.npmjs.com/package/extend) module into core. This fixes the flat extend behavior when using `util._extend` in `defaults` for any other object key that the `headers`.
Let me know what do you think.
=> Use the `extend` module to deep extend when using the defaults method

README.md
The `ca` option in https://nodejs.org/api/tls.html#tls_tls_connect_options_callback indicates that the certificate presented must be signed by one of the certificates provided. The existing wording in request led me to believe that setting it augmented the list of acceptable certificates rather than replacing it.
This caused a problem when we switched from a testing environment which used a self-signed certificate to a staging environment which used a third-party signed certificate.
=> Clarify the nature of setting `ca` in `agentOptions`

request.js, tests/test-form-urlencoded.js
Fixes https://github.com/request/request/issues/1644
=> Allow content-type overriding when using the `form` option

request.js, tests/test-form-urlencoded.js
Fixes https://github.com/request/request/issues/1630
It turned out that when the body is set via the `.form()` method the `content-length` is not being set, and therefore the request is sent as `transfer-encoding:'chunked'` which may cause problems with some servers.
So I refactored out the logic responsible for setting up the `content-length`:
```js
function setContentLength () {
if (!Buffer.isBuffer(self.body) && !Array.isArray(self.body)) {
self.body = new Buffer(self.body)
}
if (!self.hasHeader('content-length')) {
var length = (Array.isArray(self.body))
? self.body.reduce(function (a, b) {return a + b.length}, 0)
: self.body.length
if (length) {
self.setHeader('content-length', length)
} else {
self.emit('error', new Error('Argument error, options.body.'))
}
}
}
```
Much sexier than …
=> Fix form method

README.md, lib/helpers.js, request.js, tests/test-agent.js
Fixes https://github.com/request/request/issues/1637
Fixes https://github.com/request/request/issues/1669
Feedback: @mikeal @devTristan @triccardi-systran and anyone else interested in
- Take a look at the agent tests [here](https://github.com/simov/request/blob/agent-docs/tests/test-agent.js). Just a bunch of simple use cases, also note that the `forever` option defaults to `http(s).Agent` in node 0.12+
- Take a look at the [docs](https://github.com/simov/request/tree/agent-docs#requestoptions-callback) as well. A little bit down below there is a section for `agent` related options. It would be great if you read through all of them carefully and let me know if I'm not getting something right.
=> Add tests and docs for using the agent, agentClass and agentOptions. Forever option defaults to using http(s).Agent in node 0.12+

request.js, tests/test-form-data.js, tests/test-form.js
Fixes https://github.com/request/request/issues/1684
Fixes https://github.com/request/request/issues/1685
Closes https://github.com/request/request/pull/1686
As it [turned out](https://github.com/request/request/issues/1684#issuecomment-122978907) a change in  *caseless* caused `multipart/form-data` related headers to not being set.
Thanks for the feedback everyone, and especially @garymathews for fixing it up (your commit is in this PR).
I added the missing check for the `content-type` headers in the tests.
=> Fix caseless bug - content-type not being set for multipart/form-data

request.js
Previously JSON.parse() failures was silently ignored.
Although `response.body` would still contain the invalid JSON response body as a string, instead of a JS object, it's valueable to know the JSON was invalid while debugging.
I was tempted to `.emit('error', new Error('Invalid JSON received'))` but that might be a little harse.
Any thoughts?
=> debug() when JSON.parse() on a response body fails

.gitignore, README.md, request.js, tests/test-timeout.js
It's valuable to be able to detect whether a timeout occurred on the `connect`
syscall or on the `write`/`read` syscall of an HTTP request - the former
implies that your client can't reach the server and the latter implies the
server might not have responded.
For backwards compatibility, and standardization with Unix errno codes, the
`code` property of connect timeout errors must remain as 'ETIMEDOUT'. Instead
of changing this value, add a new `connect` property on timeout errors, which
is set to true if the error occurred on the `connect` attempt. Clients have
to opt in to checking it - in the common read timeout case, it will be set to
`false`.
Updates the documentation around each timeout to clarify what is going on, and
what situations can trigger each timeout.
Updates the README with …
=> Add ability to detect connect timeouts

request.js
Due to changes in io.js v3.0 creating Buffer from Object throws an Error. This PR just prevents this
=> Do not create Buffer from Object in setContentLength(iojs v3.0 issue)

index.js, request.js, tests/test-pool.js
Fixes https://github.com/request/request/issues/1709
Makes `forever` option work fine in node > 0.10, so now it doesn't create new agent every request, and reuse old agents. Issue https://github.com/request/request/issues/1709.
=> Fix forever option in node > 0.10 #1709

request.js
The implementation is very naive and aim to solve https://github.com/request/request/issues/1732.
I am not sure about writing tests as I am not fluent with tape. If necessary I can try spend time on it.
=> Avoid useless Buffer transformation

index.js, tests/test-defaults.js
Fixes https://github.com/request/request/commit/ae403dcf92e196991dc1f90a275b794fbf44d260#commitcomment-12808144
=> Fix options not being initialized in defaults method

README.md
I merged PR #884 but it was a mistake. `tough-cookie` is builtin and required by `request` for a while. There is no need for user to install it manually. So I revert the PR. Sorry for confusion.
=> Revert doc about installation of tough-cookie added in #884

request.js, tests/test-unix.js
=> Query strings now cooperate with unix sockets

request.js, tests/test-defaults.js
Will set the header when using `json: true` without a body.
Fixes #1759
=> Set default application/json content-type when using json option

package.json
:rocket:
har-validator just published version 2.0.2, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
The new version differs by 12 commits (ahead by 12, behind by 0).
- [46efd17](https://github.com/ahmadnassri/har-validator/commit/46efd17253a81fb70614e904d9e766aa4de4f394): 2.0.2
- [a873200](https://github.com/ahmadnassri/har-validator/commit/a873200f0b16de7fffcff88c0ef627cc623ef817): fix(CLI): Promise catch methods joined into one catch all method (remenants of Bluebird)
- [95861d4](https://github.com/ahmadnassri/har-validator/commit/95861d4f049475220a25352735dfd9937197bc18): 2.0.1
- …
=> Updated har-validator to version 2.0.2

request.js
Code seems to be running _qs.stringify twice for no reason.
=> Run stringify once

request.js
As mentionned in issue #1817 I've extracted the portion of `Request#onRequestResponse` that reads the response's body into `Request#readResponseBody`.
=> Extract `readResponseBody` method out of `onRequestResponse`

package.json
One of the things included in 5.2.0 is a `sort` option to stringify query strings sorted.
=> Updated qs dependency to 5.2.0

lib/auth.js, tests/test-digest-auth.js
Current implementation does not handle the RFC 2617 MD5-sess algorithm. I've added that ability along with a simple test. I've also confirmed this is working against an IIS server ( the only real-world test I have  at my disposal ).
=> Implement support for RFC 2617 MD5-sess algorithm.

lib/cookies.js, package.json, tests/test-cookies.js
tough-cookie 2.1.0 got a loose cookie mode which is more how browsers actually behave. It implies an empty key for value-only cookies.
Not sure how request handles strict spec-compliance vs. practicality, so I thought I'd just get this started with a PR.
=> Enable loose cookie parsing in tough-cookie

request.js, tests/test-isUrl.js
If href was never defined in an original, dynamically generated request options object the rest of the code referencing href fails.
=> Set href as request.js uses it

lib/tunnel.js
Unless `portA` is on purpose? ;)
=> Tunnel: fix wrong property name

lib/redirect.js, request.js, tests/test-redirect.js
Fixes #1304
Closes https://github.com/request/request/pull/1451
The problems I found before the fix: 
1. _updateProtocol was incorrect and is redundant with init(). 
2. The code was mixing configuration (options.agentClass) with state (self.agentClass). In my opinion, it would be better if the configuration is immutable which shouldn't be deleted on redirection.
=> Reuse request agent on redirect

lib/redirect.js, tests/test-redirect.js
I have no idea how this has gone unnoticed for so long. Here is how our single test regarding that behavior looks like before and after the change using `request-debug`:
> should have the referer when following redirect by default
```diff
{ request: 
{ debugId: 1,
uri: 'http://localhost:6767/temp',
method: 'POST',
headers: 
{ cookie: 'foo=bar',
host: 'localhost:6767',
'content-length': 0 } } }
{ redirect: 
{ debugId: 1,
statusCode: 301,
headers: 
{ location: 'http://localhost:6767/temp_landing',
'set-cookie': [Object],
date: 'Fri, 23 Oct 2015 08:38:55 GMT',
connection: 'close',
'transfer-encoding': 'chunked' },
uri: 'http://localhost:6767/temp_landing' } }
{ request: 
{ debugId: 1,
uri: 'http://localhost:6767/temp_landing',
method: 'GET',
headers: 
{ cookie: 'foo=bar; ham=eggs',
- …
```
=> Fix Referer header to point to the original host name

request.js
I'm not sure if this is some sort of witchcraft that I'm not familiar with, but I would normally not call the parent constructor twice as it have been done now for about a year since ef4016f.
If this is indeed on purpose I think it's one of those rare occasions that deserves a code-comment explaining it :wink:
=> Remove redundant call to Stream constructor

README.md, tests/test-redirect.js
Closes https://github.com/request/request/issues/1858
=> Improve referer header tests and docs

lib/har.js, tests/fixtures/har.json
Fixes https://github.com/request/request/issues/1872
=> Implement loose matching for har mime types

README.md, lib/tunnel.js, request.js, tests/test-tunnel.js
Current stable module cannot handle https-to-http redirection with proxy properly.
When redirected from https to **http** with `options.tunnel = undefined`,
the **http** request should be proxied without CONNECT tunneling.
This pull-request includes these changes:
1. use initial `options.tunnel` again after redirection.
2. fix test case for https-to-http redirection.
3. fix description about `tunnel` option.
Closes #1881
=> Fix tunneling after redirection from https (Original: #1881)

package.json, request.js, tests/test-bearer-auth.js, tests/test-pipes.js
Hello
Working on a propitiatory piece of app the other day, I ran into a strange exception happening on nextTick. This exception would complain of **can not call method request of undefined**. When I inspected the problem deeply I understood the problem was that the URI which I passed to **request** did not have any protocol defined, like **/bad-uri** but also the problem seemed to be triggered because a stream was piped to **request** to upload some files to a WebDAV server. I also confirmed that **request** did in fact call my callback with provided exception error but was still trying to make the actual HTTP request regardless. The exception happened because initialization was failed thus leaving **undefined** variables behind but this case of error was never checked in …
=> Error on initialization should prevent actual HTTP request from being sent

package.json, request.js, tests/test-body.js
Fixes #1904 
This bug was introduced in #1733 regarding this issue #1732
Bringing back the code that was removed in #1733. Converting to Buffer happens only when the body is a typed array. That way this won't affect the performance fix for #1732
One additional dependency was needed [is-typedarray](https://www.npmjs.com/package/is-typedarray)
=> Convert typed arrays into regular buffers

lib/tunnel.js
Fixes https://github.com/request/request/issues/1886
This change is to address the issue https://github.com/request/request/issues/1886
=> Remove content-length and transfer-encoding headers from defaultProxyHeaderWhiteList

request.js
Not documented public method: https://github.com/nodejs/node/issues/4226
There is no abort method and this causes some issues here: #1953 
Also not covered by our tests: https://codecov.io/github/request/request/request.js?ref=23fa4417ced5ee53105aef9a5c5a3f9fd56c3f9b#l-1047
Fixes https://github.com/request/request/issues/1588
Closes https://github.com/request/request/issues/1953
=> Use IncomingMessage.destroy method

request.js, tests/test-form-data-error.js
When creating a POST request with form data where the contents of the form data comes from http.IncomingMessage stream from another HTTP response, sometimes the length of the request cannot be calculated.  One case is when the IncomingMessage is a chunked response.  Then the form-data module cannot calculate the length until the stream is fully read, and it returns NaN in getLength() callback.  The header Content-Length should not be set in such situation, otherwise the remote server returns with 400.
Ran into this problem a lot while processing the responses from google drive servers as they tend to send chunked response.
=> Check form-data content-length value before setting up the header

lib/har.js, request.js
Fixes https://github.com/request/request/issues/1997
See also https://github.com/npm/npm/issues/11104
=> Use the `extend` module instead of util._extend

lib/multipart.js, tests/test-multipart.js
Closes https://github.com/request/request/pull/2018
=> Convert numeric multipart bodies to string

CHANGELOG.md, README.md, package.json, request.js, tests/test-aws.js
Closes https://github.com/request/request/pull/2031
- [AWS Signature Version 4](http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html
https://www.npmjs.com/package/aws4)
- [aws4](https://www.npmjs.com/package/aws4) module
=> Add AWS Signature Version 4

package.json
It was moved in #2036 as a devDependency, but is still used in
request.js
This should fix #2040.
=> restore aws4 as regular dependency

README.md, request.js, tests/test-stream.js
=> Accept read stream as body option

README.md, lib/helpers.js, request.js, tests/test-json-request.js
Adds support for the replacer argument of JSON.stringify, in the same
way that request already supports the revivier argument for JSON.parse.
=> Support JSON stringify replacer argument.

.travis.yml, request.js, tests/test-headers.js
=> Catch errors from the underlying http module

README.md
I also noticed there're two badges for Coverage, one pointing to Codecov and the other one to Coveralls. Is this intended or one should not be used?
=> Fix TravisCI badge reference master branch

request.js, tests/test-headers.js
Fixes #2120
Also see https://github.com/request/request/issues/2120#issuecomment-208954497 and https://github.com/request/request/issues/2164
=> Check for self.req existence inside the write method

request.js
This fixes the issue mentioned in #1723. The lifetime of the buffer variable defined in `readResponseBody` is linked to the Request object. This can lead to leaky behavior if references to the request persist in memory.
Fixes #1723
=> Explicitly destroy request buffer

README.md, index.js, tests/test-api.js
Just another useful way to pass the request's callback.
=> Add callback option

request.js, tests/test-gzip.js
Fixes https://github.com/request/request/issues/2171
=> Add support for deflate content encoding

request.js, tests/test-gzip.js
=> Do not try to pipe Gzip responses with no body

tests/test-httpModule.js, tests/test-redirect-auth.js, tests/test-redirect-complex.js, tests/test-redirect.js
when running the coverage report (in single process)
=> Use server-destory to close hanging sockets

package.json, request.js, tests/test-form-data-error.js
Closes https://github.com/request/request/pull/2160
Closes https://github.com/request/request/issues/1832
This is a temporary solution until form-data@2.0 starts stringifying null values. See https://github.com/form-data/form-data/issues/147
=> Update to form-data RC4 and pass null values to it

request.js
The "socket._httpMessage.emit('error', error)" line currently throws when the keep-alive period expires and the socket resets, after a redirect to a different host. This is because the listener on the socket is never cleaned up, and the socket no longer has _httpMessage (the ClientRequest is long gone). This is bug #1903, which is also responsible for npm/npm#9984.
It looks to me like node core correctly re-emits socket error events on _httpMessage now, so we shouldn't have to. Looking at core I also cannot even find a "res" property on socket - if there's a reason to leave this, please speak up.
Closes https://github.com/request/request/issues/1903
=> Remove connectionErrorHandler to fix #1903

package.json
To address https://nodesecurity.io/advisories/130
=> Update tough-cookie to 2.3.0

tests/test-form-data-error.js
Upstream change broke this unit test. Fixed this in another PR and realized that it's probably better off as it's own PR.
`form-data` just released 1.0.0, and it changed the order of property lookup what triggers a `TypeError` when we push up a null form-data property. This change just checks that it throws a `TypeError` instead of checking the string.
[Upstream code change link](https://github.com/form-data/form-data/compare/v1.0.0-rc4...v1.0.0#diff-121026c01234c71e2b3b316f7abc5afcR213)
=> Check error type instead of string

request.js, tests/test-timing.js
When `time:true` is set in options, elapsedTime is added to the response object.
This PR will _also_ include `responseStartTime`, the timestamp when the response begins. With this moment tagged, we can now recreate a rich network waterfall of the network activity. 
For example, here's a network waterfall of some project's `npm install` with this patch and [`request-capture-har`](https://github.com/paulirish/node-request-capture-har):
=> Add responseStartTime timing

index.js, lib/helpers.js
There's already precedent for function `typeof` checks - in fact there are more of them, than `isFunction` calls.
=> Remove "isFunction" helper in favor of "typeof" check

request.js
In doing stress testing on my application, started seeing these messages in my logs:
```
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at IncomingMessage.addListener (events.js:239:17)
at IncomingMessage.Readable.on (_stream_readable.js:680:33)
at Request.onRequestResponse (...node_modules/request/request.js:896:14)
at emitOne (events.js:82:20)
at ClientRequest.emit (events.js:169:7)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:433:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
at Socket.socketOnData (_http_client.js:322:20)
```
```
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to …
```
=> change .on to .once, remove possible memory leaks

request.js
This PR fixes a timeout-related compatibility issue with node v6.8.0+ and makes the connection and request/response timeout more accurate by starting them at more appropriate times.
=> Improve timeouts accuracy and node v6.8.0+ compatibility

package.json, request.js
`bl` does a lot, but `request`'s needs are pretty simple. This PR removes `bl` in favor of operating on buffers directly. There is no change in functionality here - `bl` also calls `Buffer.concat` when slicing an all buffer `BufferList`.
=> Handle buffers directly instead of using "bl"

tests/test-timeout.js
This commit should allow the 'connect timeout' test to pass more often than not.
=> Improve test-timeout reliability

README.md, lib/redirect.js, tests/test-redirect.js
Hey 👋
closes #2118
You can set `followOriginalHttpMethod` to follow the original HTTP method.
The problem was that request followed the requests with a hardcoded HTTP method.
---
An alternative solution would be to always redirect to the original HTTP method. Tell me what do you prefer and i will update my PR 👍
=> Add followOriginalHttpMethod to redirect to original HTTP method

request.js, tests/test-timeout.js
Fixes: https://github.com/request/request/issues/2438
/cc @mdlavin Can you try this patch?
=> Fix socket 'connect' listener handling

tests/test-timeout.js
This is basically https://github.com/request/request/pull/2414 except applied to a recently added test that was merged *before* https://github.com/request/request/pull/2414.
=> Make other connect timeout test more reliable too

request.js, tests/test-gzip.js
Be explicitly lenient with gzip decompression by always requesting
`zlib` to flush the input data and never explicitly ending the
`zlib` input.
The behavioural difference is that on Node ≥ 6, which has a slightly
stricter gzip decoding process than previous Node versions, malformed
but otherwise acceptable server responses are still properly
decompressed (the most common example being a missing checksum
at the stream end).
This aligns behaviour with cURL, which always uses the `Z_SYNC_FLUSH`
flag for decompression.
On the downside, accidental truncation of a response is no longer
detected on the compression layer.
Ref: https://github.com/nodejs/node/issues/8701#issuecomment-268224481
=> More lenient gzip decompression

package.json
I'm in the process of teaching my students about how to do PRs, and trying @mafintosh's [first PR idea](https://twitter.com/mafintosh/status/782288714785492992) with them.  As I was writing up an example for their lab, I noticed that the `package.json` here uses `tags` vs. `keywords.
This fixes it to properly include the existing keywords, which aren't currently being picked up by npmjs, see:
=> Change tags to keywords in package.json

README.md
When i read request arguments specification for first time, i didn't recognize that IncomingMessage is created by ClientRequest and passed as the first argument 'request' or 'response', i think this reference in readme improve this great package :D
=> Adding a simple Response object reference in argument specification

request.js, tests/test-headers.js
Fixes #2292
When using IPv6 addresses in URLs, the address must be enclosed in brackets, e.g.`https://[::1]:3000/headers.json`
Likewise, when using IPv6 addresses in `Host` header values, the address again must be enclosed in brackets, e.g. `Host: [::1]:3000`
When the **request** module adds the `Host` header value, it does so using the `hostname` and `port` (if needed) parts of the parsed URL.  However, this approach does not correctly format IPv6 addresses with the necessary enclosing brackets as `hostname` does not include them.
If you were instead to utilize the `host` portion of the parsed URL instead, you would automatically get the correctly bracketed value, potentially plus the port.  My testing has not shown any case where the port was unnecessarily included in the `host` value …
=> Correctly format the Host header for IPv6 addresses

package.json
bump up har-validator version to fix #2572
=> fixes #2572

lib/helpers.js, lib/multipart.js, lib/oauth.js, package.json, request.js
Tests have run and passed locally but I'm curious to see what CI says because I haven't tested against older versions of Node.js yet.
I ended up having to push a quick release of `tunnel-agent` to cover this potential vulnerability fully. There are no tests for `tunnel-agent` so that only way to get any coverage was to push a release and then pull that new release into this PR.
=> Migrating to safe-buffer for improved security.

README.md, request.js, tests/test-timing.js
Feedback from @mcorb in https://github.com/request/request/pull/2452 found a few items with the new `.timings` object.
Changes:
1. The [`net` `'lookup'`](https://nodejs.org/api/net.html#net_event_lookup) event is now tracked, which is the correct event to track DNS lookup time.
2. There is a new `.timingStart` property that is based on `Date.now()`.
3. The `.timings.*` timestamps are relative to `.timingStart` (using `now()`).
4. The `.timings` object now only contains `socket`, `lookup`, `connect`, `response` and `end` (moving the durations to `.timingPhases`)
5. `.timings.start` is no longer needed, since it will always in effect be `0`.
6. The other durations such as `wait`, `dns`, `tcp`, etc were moved to `.timingPhases`.
7. A new `.timingPhases.wait` delta is added, which tracks the …
=> Timings: Tracks 'lookup', adds 'wait' time, fixes connection re-use

lib/helpers.js, lib/multipart.js, lib/oauth.js, package.json, request.js
The last PR for safe-buffer didn't actually migrate to the new APIs. I had assumed it would zero-fill by default but I was incorrect.
=> safe-buffer doesn't zero-fill by default, its just a polyfill.

package.json
a simple `npm install request` resulted in a `babel` install due to usage as a `devDependency` in `har-validator`, so `har-validator` is now refactored to remove that dependency entirely, making `request` lighter to install _(if only slightly)_ :)
=> chore(dependencies): har-validator to 5.x [removes babel dep]

tests/test-timing.js
Adds an additional KeepAlive test for https://github.com/request/request/pull/2566, increasing test coverage.
=> Adds test-timing keepAlive test

README.md
Should counter the opinion that request "doesn't support promises" and help users find these helper libraries. Promises will only get more and more popular as async/await gains support.
/cc @mikeal
=> Add promise support section to README

index.js, package.json, tests/test-options-convenience-method.js
Hey guys,
I'm currently working on a feature that involves a HTTP OPTIONS request. I really appreciate the convenience methods as they are easy to stub with my library of choice (Sinon).
I noticed that there is not an equivalent for HTTP OPTIONS, so I've added one. There may be a reason why this hasn't been exposed already, but implementing it didn't impact any of the existing tests, plus searching the existing PRs and issues didn't suggest anything.
My PR also has new version number (i.e. new minor revision), but this is merely a suggestion; I'm sure you'll have your own processes surrounding this.
Let me know if you have any questions or thoughts.
Thanks,
James
=> Add convenience method for HTTP OPTIONS

package.json
This addresses:
```
The tough-cookie module is vulnerable to regular expression denial of service. Input of around 50k characters is required for a slow down of around 2 seconds.
Unless node was compiled using the -DHTTPMAXHEADER_SIZE= option the default header max length is 80kb so the impact of the ReDoS is limited to around 7.3 seconds of blocking.
At the time of writing all version <=2.3.2 are vulnerable
```
- See: https://www.versioneye.com/Node.JS/tough-cookie/2.3.2
- Also tough-cookie:
- https://github.com/salesforce/tough-cookie/pull/97
- https://github.com/salesforce/tough-cookie/pull/92
=> Updating tough-cookie due to security fix.

package.json, request.js, tests/test-hawk.js
=> Update hawk to 7.0.7

lib/oauth.js, tests/test-oauth.js
- If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
FIxes https://github.com/request/request/issues/2792
=> Fixed calculation of oauth_body_hash, issue #2792

tests/test-headers.js
- [Y] I have run `npm test` locally and all tests are passing.
- [Y] I have added/updated tests for any new behavior.
- [Y] If this is a significant change, an issue has already been created where the problem / solution was discussed: https://github.com/request/request/issues/2877
This is a suggestion of alterations to test-headers.js to unblock CI again, given there are a number of consistently failing tests there for some months now.
I've changed the invalid header characters test, so that it passes with _either_ the old or new message returned by node.
I've altered the IPv6 header test, so that if the underlying OS doesn't support IPv6 the test doesn't run.
=> Alterations for failing CI tests

tests/test-headers.js
These are not going to fail if there is a server listening on those ports.
Introduced here https://github.com/request/request/pull/2904
=> Fix header tests

.github/stale.yml
This will help me mark issues that should stick around but don't fit into the previously two listed categories.
=> Add neverstale label to stalebot config

.travis.yml, package.json
Node.js v4 reached its EOL a few months ago. Updated package.json and travis.yml to use Node.js v6 and later. One thing to note, I ran `npm test` and I did get failing tests, however they fail on master as well.
=> Drop support for Node.js v4 (Fix #2917)

request.js
This is the workaround proposed in issue #2807.
=> Ignore ECONNRESET errors from a destroyed socket

request.js
Reverts request/request#2808
It hadn't been rebased in a long time, needs to be rebased and the tests to pass.
=> Revert "Ignore ECONNRESET errors from a destroyed socket"

index.js
When `options=null`, `extend(params, options, {uri: uri})` is not entered, but `extend(params, uris)`
=> optimize:do unnecessary processing when changing options to null

README.md
Timeout argument description is currently very misleading. It was split into [two bullets here](https://github.com/request/request/pull/2728) but the note regarding OS-wide timeout does not apply to the first bullet, but rather the second. In addition, [this change](https://github.com/request/request/pull/1392/files) made the wording more confusing, in my opinion. I reverted it back to what it was originally.
=> Update README timeout

CHANGELOG.md
I want to need the CHANGELOG.md about the latest version 2.88.0.
Now I'll update the `request` module to latest version on our projects but I cannot see the "Change Log" on CHANGELOG.md.
Please review this pull request when you have a time.
Thanks!
Used the following command:
```
github-changes -o request -r request -b master --date-format '(YYYY/MM/DD)' --only-pulls --use-commit-body --auth
```
=> Updated the Change Log for v2.88.0

.gitignore, package.json
istanbul package is not longer maintained
- Removed `istanbul` package and replaced it with `nyc` package.
- Modified the test coverage script so it uses the new package.
- Added the coverage output folder to the list of files ignored by git.
=> Use nyc instead of istanbul
