README.md
package.json
tests/test-oauth.js

@nylen I was faster :zap: 
related to https://github.com/request/oauth-sign/pull/12

Add support for OAuth plaintext signature method

---

package.json

Follow up of #1189 where dependency upgrades were discussed.

Update hawk dependency to ~2.3.0

---

tests/test-pipes.js

Test request body and with/without content-length header.  See #1394.

Improve pipe-from-file tests

---

lib/multipart.js
tests/test-multipart.js

Fixes https://github.com/request/request/pull/1423#discussion_r27093927

Fix multipart boundary extraction regexp

---

tests/test-pool.js

currently failing
Closes https://github.com/request/request/issues/1511

forever+pool test

---

README.md

Adding dependency status bar to README.md to make it easier to identify when one or more dependencies are out of date.

Adding dependency status bar to README.md

---

index.js
tests/test-defaults.js

Fixes https://github.com/request/request/issues/1537

Fix recursive defaults for convenience methods

---

request.js
tests/test-errors.js

Move getProxyFromURI logic below the check for Invaild URI (#1595)

---

lib/redirect.js
tests/test-redirect.js

Fixes https://github.com/request/request/issues/1649

Preserve HEAD method when using followAllRedirects

---

request.js
tests/test-defaults.js
tests/test-json-request.js

Fixes https://github.com/request/request/issues/1783
Fixes #1786

Revert: Set default application/json content-type when using json option #1772

---

package.json

:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
<sub>
</sub>

Updated bluebird to version 2.10.1

---

package.json

:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
<sub>
</sub>

Updated karma-cli to version 0.1.1

---

package.json

:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
<sub>
</sub>

Updated tape to version 4.2.0

---

package.json

:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
<sub>
</sub>

Updated karma-browserify to version 4.4.0

---

package.json

:rocket:
tough-cookie just published version 2.1.0, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
<sub>
</sub>

Updated tough-cookie to version 2.1.0

---

package.json

See https://nodesecurity.io/advisories/76

Update har-validator dependency for nsp advisory #76

---

package.json

Fixes https://github.com/request/request/pull/2050
Closes https://github.com/request/request/pull/2049

Up bluebird and oauth-sign

---

README.md
package.json

Fix badges

---

README.md
index.js
tests/test-defaults.js

Add 'delete' alias for the 'del' API method

---

package.json

Add greenkeeper ignored packages

---

lib/helpers.js

Removed unneeded `deferMethod` wrapper function.

Simplify "defer" helper creation

---

tests/test-pool.js

This really looks like a typo. I didn't run the tests locally, will see if it still passes CI.

Fix typeof check in test-pool.js

---

package.json

- `v3.x` introduces massive performance improvement.
- `v4.x` minimizes dependencies.

dependency(har-validator): update to ~v4.2.0

---

README.md

Small change, but it's easy to copy and paste this example, change the URL, and get a completely silent and confusing callback. We saw this in https://github.com/request/request/issues/2557.

Update README.md example snippet

---

package.json

Fix vulnerability alert, see the recommendation https://snyk.io/vuln/npm%3Aqs%3A20170213

Security issue: Upgrade qs to version 6.4.0

---

README.md

fix tabulation on request example README.MD

fix tabulation on request example README.MD

---

README.md

I realized that there is a README section on the request convenience methods after merging #2541, so I made a quick update to that section to simplify it (no need for it to be so long) and update it (add the newest `request.options()` method).
/cc @jamesseanwright

Update README to simplify & update convenience methods

---

README.md

- [N/A] I have run `npm test` locally and all tests are passing.
- [N/A] I have added/updated tests for any new behavior.
- [N/A] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
This pull request fixes some text to be more consistent in README.md

Fixed some text in README.md

---

package.json
tests/test-oauth.js

#2627 
Bump the version of `oauth-sign` to 0.9.0

Update to oauth-sign 0.9.0

---

.github/stale.yml

There are a few years of stale issues and prs. This bot will close issues over a year old and give people a chance to respond if they think the issue should stay open. After a manual review of more recent issues, we should tighten this down to 60 or 90 days.
https://probot.github.io/apps/stale/

chore: Add probot-stale

---

README.md

- [N/A] I have added/updated tests for any new behavior.
- [N/A] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
Update README.md to mention that util.promisify can be used to convert a regular function that takes a callback to return a promise instead.

Update README to mention util.promisify()

---

README.md

Update tough cookie store API doc link

Update cookie store API link

---

README.md

Update the documentation of `timeout` to reflect it controls timeout of socket inactivity.

Update the documentation of timeout

---

tests/test-pipes.js

Added missing assertion to a test in `test-pipes.js`

Added missing assertion in test-pipes

---

README.md

fix: use const instead of var in the README

---

tests/test-pipes.js

chore: ensure piped body is exactly the same

---

lib/getProxyFromURI.js

- [N/A] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
Just fixing a broken link

Update outdated link in comment

---

README.md

doc: note full deprecation

---

README.md

README: typo in deprecation message
